### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [solmatas/Bitter#7]
@solmatas @alexeiva 

Hello Sol and Alexie,

As you may know, the Google fonts team would love to see a variable fonts version of ‘**Bitter**'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

We wish to begin by making a fork off of this git repository. 

Dave Crossland mentioned that the Bitter family may have had some updates, and that the data may be different than the three styles currently being served on fonts.google.com

First, we wish to confirm the location of the most current source data.
Is there now a Black style?  Is there a Bold Italic?  See the attached screenshot where the styles available for download differ from the specimen.
Thank you in advance for directing us to the best sources : )

A little bit about the process...

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

The upgrade will be completed for you in the near future. When the proposed final font is approved by Google will you accept a pull request?

We hope this answers some of your questions. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

![Bitter via Huerta](https://user-images.githubusercontent.com/6576107/67708327-58b04800-f992-11e9-886a-cdf09bfc886d.png)

**Comment by solmatas** [comment]
Hi Jill,

Let me check the last files we have and I will send you the most current source data in the next days.

Best,
Sol

**Comment by pichotta** [comment]
Hi Sol,  

Thank you for checking on your latest source files of Bitter. We are ready to start when you are : )

Best,
Jill

**Comment by pichotta** [comment]
@solmatas

Hi Sol,
Just checking in to see if you had any luck finding the latest source data for Bitter?
Thanks,
Jill

**Comment by solmatas** [comment]
Hi Jill,

Yes I have them and I am making some corrections on the files. I will send them at the latest by next week.
Sol.

**Comment by pichotta** [comment]
Hi Sol,

Thank you for the update : ) That sounds good. We look forward to the updated sources next week.

Best,

Jill

**Comment by pichotta** [comment]
Hi Sol,

We will be happy to review your latest corrections to Bitter when you are ready : )

**Comment by pichotta** [comment]
@solmatas 
Hi Sol,

Do you have a new estimate when the latest and greatest **Bitter** data will be posted?

Thanks!
Jill

**Comment by pichotta** [comment]
@solmatas

Hi Sol,

We are running up against a deadline on our end. Do you have an update on the Bitter expansion? 
: )

Thank you,

Jill

**Comment by solmatas** [comment]
Hi Jill,

sorry for the delayed answer. I have been traveling in the last weeks.
Still working on some detail on the italics. I can upload Normal width. Otherwise I need three more days to upload everything.

Cheers,
Sol

**Comment by pichotta** [comment]
Hi Sol,

Thank you for the update. We will wait for all the styles of **Bitter** to be uploaded. Wishing you the best of Holidays!

Jill

**Comment by pichotta** [comment]
Hi Sol,

Do you have an update on the data for the Bitter expansion?  Thank you : )

Jill

**Comment by solmatas** [comment]
Hi Jill,
sorry for the delay.
I created a new repository with the new expansion of Bitter:
https://github.com/solmatas/BitterPro

Thanks,
Sol

**Comment by pichotta** [comment]
Hi Sol,

Thank you very much for the updated data for the Bitter expansion and the new git repository : )

Best,

Jilll
